package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OriginType generated by hbm2java
 */
public class OriginType extends FarmObjectImpl {

	private Integer id;
	private String originType;
	private String description;
	private Farm farm;
	private Set livestocks = new HashSet(0);

	public OriginType() {
	}

	public OriginType(String originType, Farm farm) {
		this.originType = originType;
		this.farm = farm;
	}

	public OriginType(String originType, String description, Farm farm, Set livestock) {
		this.originType = originType;
		this.description = description;
		this.farm = farm;
		this.livestocks = livestocks;		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOriginType() {
		return this.originType;
	}

	public void setOriginType(String originType) {
		this.originType = originType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getLivestocks() {
		return this.livestocks;
	}

	public void setLivestocks(Set livestocks) {
		this.livestocks = livestocks;
	}
	
	@Override
	public String toString() {
		return originType;
	}

}
