package com.dblue.farm;

// Generated Jul 18, 2012 9:21:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VendorType generated by hbm2java
 */
public class VendorType extends FarmObjectImpl  {

	private Integer id;
	private String vendor;
	private String description;
	private Set vendors = new HashSet(0);
	private Farm farm;

	public VendorType() {
	}

	public VendorType(String vendor, Farm farm) {
		this.vendor = vendor;
		this.farm = farm;
	}

	public VendorType(String vendor, Set vendors, Farm farm) {
		this.vendor = vendor;
		this.vendors = vendors;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}
	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getVendors() {
		return this.vendors;
	}

	public void setVendors(Set vendors) {
		this.vendors = vendors;
	}	

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	@Override
	public String toString() {
		return vendor;
	}
	
	

}
