package com.dblue.farm;

// Generated Aug 22, 2012 6:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Ingredient generated by hbm2java
 */
public class Ingredient extends FarmObjectImpl  {

	private Integer id;
	private Farm farm;
	private IngredientType ingredientType;
	private BigDecimal tdn;
	private BigDecimal cp;
	private BigDecimal udp;
	private BigDecimal rdp;
	private BigDecimal ca;
	private BigDecimal p;
	private BigDecimal rate;

	public Ingredient() {
	}

	public Ingredient(Farm farm, IngredientType ingredientType, BigDecimal tdn,
			BigDecimal cp, BigDecimal udp, BigDecimal rdp, BigDecimal ca,
			BigDecimal p, BigDecimal rate) {
		this.farm = farm;
		this.ingredientType = ingredientType;
		this.tdn = tdn;
		this.cp = cp;
		this.udp = udp;
		this.rdp = rdp;
		this.ca = ca;
		this.p = p;
		this.rate = rate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public IngredientType getIngredientType() {
		return this.ingredientType;
	}

	public void setIngredientType(IngredientType ingredientType) {
		this.ingredientType = ingredientType;
	}

	public BigDecimal getTdn() {
		return this.tdn;
	}

	public void setTdn(BigDecimal tdn) {
		this.tdn = tdn;
	}

	public BigDecimal getCp() {
		return this.cp;
	}

	public void setCp(BigDecimal cp) {
		this.cp = cp;
	}

	public BigDecimal getUdp() {
		return this.udp;
	}

	public void setUdp(BigDecimal udp) {
		this.udp = udp;
	}

	public BigDecimal getRdp() {
		return this.rdp;
	}

	public void setRdp(BigDecimal rdp) {
		this.rdp = rdp;
	}

	public BigDecimal getCa() {
		return this.ca;
	}

	public void setCa(BigDecimal ca) {
		this.ca = ca;
	}

	public BigDecimal getP() {
		return this.p;
	}

	public void setP(BigDecimal p) {
		this.p = p;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

}
