package com.dblue.farm;

// Generated Sep 15, 2012 12:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Statistics generated by hbm2java
 */
public class Statistics extends FarmObjectImpl {

	private Integer id;
	private String height;
	private String weight;
	private String length;
	private String appearance;
	private String production;
	private BigDecimal fatPercent;
	private BigDecimal purchasePrice;
	private String purchaseLocation;
	private Date purchaseDate;
	private String transportationDist;
	private BigDecimal transportationCost;
	private String purchaseFarm;
	private String purchaseBroker;
	private Set livestocksForCurrentStatId = new HashSet(0);
	private Set livestocksForPurchaseStatId = new HashSet(0);

	public Statistics() {
	}

	public Statistics(String height, String weight, String length,
			String appearance, String production, BigDecimal fatPercent,
			BigDecimal purchasePrice, String purchaseLocation,
			Date purchaseDate, String transportationDist,
			BigDecimal transportationCost, String purchaseFarm,
			String purchaseBroker, Set livestocksForCurrentStatId,
			Set livestocksForPurchaseStatId) {
		this.height = height;
		this.weight = weight;
		this.length = length;
		this.appearance = appearance;
		this.production = production;
		this.fatPercent = fatPercent;
		this.purchasePrice = purchasePrice;
		this.purchaseLocation = purchaseLocation;
		this.purchaseDate = purchaseDate;
		this.transportationDist = transportationDist;
		this.transportationCost = transportationCost;
		this.purchaseFarm = purchaseFarm;
		this.purchaseBroker = purchaseBroker;
		this.livestocksForCurrentStatId = livestocksForCurrentStatId;
		this.livestocksForPurchaseStatId = livestocksForPurchaseStatId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getAppearance() {
		return this.appearance;
	}

	public void setAppearance(String appearance) {
		this.appearance = appearance;
	}

	public String getProduction() {
		return this.production;
	}

	public void setProduction(String production) {
		this.production = production;
	}

	public BigDecimal getFatPercent() {
		return this.fatPercent;
	}

	public void setFatPercent(BigDecimal fatPercent) {
		this.fatPercent = fatPercent;
	}

	public BigDecimal getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public String getPurchaseLocation() {
		return this.purchaseLocation;
	}

	public void setPurchaseLocation(String purchaseLocation) {
		this.purchaseLocation = purchaseLocation;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public String getTransportationDist() {
		return this.transportationDist;
	}

	public void setTransportationDist(String transportationDist) {
		this.transportationDist = transportationDist;
	}

	public BigDecimal getTransportationCost() {
		return this.transportationCost;
	}

	public void setTransportationCost(BigDecimal transportationCost) {
		this.transportationCost = transportationCost;
	}

	public String getPurchaseFarm() {
		return this.purchaseFarm;
	}

	public void setPurchaseFarm(String purchaseFarm) {
		this.purchaseFarm = purchaseFarm;
	}

	public String getPurchaseBroker() {
		return this.purchaseBroker;
	}

	public void setPurchaseBroker(String purchaseBroker) {
		this.purchaseBroker = purchaseBroker;
	}

	public Set getLivestocksForCurrentStatId() {
		return this.livestocksForCurrentStatId;
	}

	public void setLivestocksForCurrentStatId(Set livestocksForCurrentStatId) {
		this.livestocksForCurrentStatId = livestocksForCurrentStatId;
	}

	public Set getLivestocksForPurchaseStatId() {
		return this.livestocksForPurchaseStatId;
	}

	public void setLivestocksForPurchaseStatId(Set livestocksForPurchaseStatId) {
		this.livestocksForPurchaseStatId = livestocksForPurchaseStatId;
	}

}
