package com.dblue.farm;

// Generated Jul 18, 2012 9:21:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor extends FarmObjectImpl {

	private Integer id;
	private Farm farm;
	private Contact contact;
	private VendorType vendorType;
	private String name;
	private String code;
	private String remarks;
	private Set expenseses = new HashSet(0);
	private Set livestocks = new HashSet(0);
	private Set purchaseses = new HashSet(0);

	public Vendor() {
	}

	public Vendor(Farm farm, VendorType vendorType, String name, String code) {
		this.farm = farm;
		this.vendorType = vendorType;
		this.name = name;
		this.code = code;
	}

	public Vendor(Farm farm, Contact contact, VendorType vendorType,
			String name, String code, String remarks, Set expenseses,
			Set livestocks, Set purchaseses) {
		this.farm = farm;
		this.contact = contact;
		this.vendorType = vendorType;
		this.name = name;
		this.code = code;
		this.remarks = remarks;
		this.expenseses = expenseses;
		this.livestocks = livestocks;
		this.purchaseses = purchaseses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public VendorType getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(VendorType vendorType) {
		this.vendorType = vendorType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set expenseses) {
		this.expenseses = expenseses;
	}

	public Set getLivestocks() {
		return this.livestocks;
	}

	public void setLivestocks(Set livestocks) {
		this.livestocks = livestocks;
	}

	public Set getPurchaseses() {
		return this.purchaseses;
	}

	public void setPurchaseses(Set purchaseses) {
		this.purchaseses = purchaseses;
	}

	@Override
	public String toString() {
		return name;
	}
	
	

}
