package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DeceaseType generated by hbm2java
 */
public class DeceaseType extends FarmObjectImpl {

	private Integer id;
	private String decease;
	private String description;
	private Farm farm;
	private Set deceases = new HashSet(0);

	public DeceaseType() {
	}

	public DeceaseType(String decease, Farm farm) {
		this.decease = decease;
		this.farm = farm;
	}

	public DeceaseType(String decease, String description, Farm farm, Set deceases) {
		this.decease = decease;
		this.description = description;
		this.farm = farm;
		this.deceases = deceases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDecease() {
		return this.decease;
	}

	public void setDecease(String decease) {
		this.decease = decease;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getDeceases() {
		return this.deceases;
	}

	public void setDeceases(Set deceases) {
		this.deceases = deceases;
	}
	
	@Override
	public String toString() {
		return decease;
	}

}
