package com.dblue.farm;

// Generated Nov 3, 2012 3:57:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * StockType generated by hbm2java
 */
public class StockType extends FarmObjectImpl {

	private Integer id;
	private StockCategory stockCategory;
	private Farm farm;
	private String stockCode;
	private String stockName;
	private BigDecimal stockMinLevel;
	private BigDecimal stockBalance;
	private Set stockAudits = new HashSet(0);

	public StockType() {
	}

	public StockType(StockCategory stockCategory, Farm farm, String stockCode,
			String stockName, BigDecimal stockMinLevel, BigDecimal stockBalance) {
		this.stockCategory = stockCategory;
		this.farm = farm;
		this.stockCode = stockCode;
		this.stockName = stockName;
		this.stockMinLevel = stockMinLevel;
		this.stockBalance = stockBalance;
	}

	public StockType(StockCategory stockCategory, Farm farm, String stockCode,
			String stockName, BigDecimal stockMinLevel,
			BigDecimal stockBalance, Set stockAudits) {
		this.stockCategory = stockCategory;
		this.farm = farm;
		this.stockCode = stockCode;
		this.stockName = stockName;
		this.stockMinLevel = stockMinLevel;
		this.stockBalance = stockBalance;
		this.stockAudits = stockAudits;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StockCategory getStockCategory() {
		return this.stockCategory;
	}

	public void setStockCategory(StockCategory stockCategory) {
		this.stockCategory = stockCategory;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public BigDecimal getStockMinLevel() {
		return this.stockMinLevel;
	}

	public void setStockMinLevel(BigDecimal stockMinLevel) {
		this.stockMinLevel = stockMinLevel;
	}

	public BigDecimal getStockBalance() {
		return this.stockBalance;
	}

	public void setStockBalance(BigDecimal stockBalance) {
		this.stockBalance = stockBalance;
	}
	
	public Set getStockAudits() {
		return this.stockAudits;
	}

	public void setStockAudits(Set stockAudits) {
		this.stockAudits = stockAudits;
	}

	@Override
	public String toString() {
		return stockName;
	}

}
