package com.dblue.farm;

// Generated Sep 15, 2012 12:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Devermitization generated by hbm2java
 */
public class Devermitization extends FarmObjectImpl {

	private Integer id;
	private Health health;
	private Farm farm;
	private DeVermitizationType deVermitizationType;
	private Date lastVermitizationDate;
	private Date nextVermitizationDate;
	private Date vermitizationDate;
	private Date manufacturedDate;
	private Date expiryDate;
	private String manufacturerName;
	private String batchNumber;

	public Devermitization() {
	}

	public Devermitization(DeVermitizationType deVermitizationType,
			Farm farm, Date lastVermitizationDate, Date nextVermitizationDate,
			Date vermitizationDate) {
		this.deVermitizationType = deVermitizationType;
		this.farm = farm;
		this.lastVermitizationDate = lastVermitizationDate;
		this.nextVermitizationDate = nextVermitizationDate;
		this.vermitizationDate = vermitizationDate;
	}

	public Devermitization(Health health,
			Farm farm, DeVermitizationType deVermitizationType,
			Date lastVermitizationDate, Date nextVermitizationDate,
			Date vermitizationDate, Date manufacturedDate, Date expiryDate,
			String manufacturerName) {
		this.health = health;
		this.farm = farm;
		this.deVermitizationType = deVermitizationType;
		this.lastVermitizationDate = lastVermitizationDate;
		this.nextVermitizationDate = nextVermitizationDate;
		this.vermitizationDate = vermitizationDate;
		this.manufacturedDate = manufacturedDate;
		this.expiryDate = expiryDate;
		this.manufacturerName = manufacturerName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Health getHealth() {
		return this.health;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public void setHealth(Health health) {
		this.health = health;
	}

	public DeVermitizationType getDeVermitizationType() {
		return this.deVermitizationType;
	}

	public void setDeVermitizationType(DeVermitizationType deVermitizationType) {
		this.deVermitizationType = deVermitizationType;
	}

	public Date getLastVermitizationDate() {
		return this.lastVermitizationDate;
	}

	public void setLastVermitizationDate(Date lastVermitizationDate) {
		this.lastVermitizationDate = lastVermitizationDate;
	}

	public Date getNextVermitizationDate() {
		return this.nextVermitizationDate;
	}

	public void setNextVermitizationDate(Date nextVermitizationDate) {
		this.nextVermitizationDate = nextVermitizationDate;
	}

	public Date getVermitizationDate() {
		return this.vermitizationDate;
	}

	public void setVermitizationDate(Date vermitizationDate) {
		this.vermitizationDate = vermitizationDate;
	}

	public Date getManufacturedDate() {
		return this.manufacturedDate;
	}

	public void setManufacturedDate(Date manufacturedDate) {
		this.manufacturedDate = manufacturedDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	public String getBatchNumber() {
		return batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

}
