package com.dblue.farm;

// Generated Nov 3, 2012 8:10:47 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * StockAudit generated by hbm2java
 */
public class StockAudit extends FarmObjectImpl {

	private Integer id;
	private StockType stockType;
	private Date auditDate;
	private String operation;
	private BigDecimal quantity;
	private Farm farm;

	public StockAudit() {
	}

	public StockAudit(StockType stockType, Date auditDate, String operation,
			BigDecimal quantity, Farm farm) {
		this.stockType = stockType;
		this.auditDate = auditDate;
		this.operation = operation;
		this.quantity = quantity;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StockType getStockType() {
		return this.stockType;
	}

	public void setStockType(StockType stockType) {
		this.stockType = stockType;
	}

	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
