package com.dblue.farm;

// Generated Sep 19, 2012 11:21:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Vaccination generated by hbm2java
 */
public class Vaccination extends FarmObjectImpl {

	private Integer id;
	private Health health;
	private Farm farm;
	private VaccineType vaccineType;
	private Date lastVaccinationDate;
	private Date nextVaccinationDate;
	private Date vaccinationDate;
	private Date manufacturedDate;
	private String vaccineBrand;
	private String manufacturerName;
	private Date vaccineExpiryDate;
	private BigDecimal dosage;

	public Vaccination() {
	}

	public Vaccination(VaccineType vaccineType, Farm farm) {
		this.vaccineType = vaccineType;
		this.farm = farm;
	}

	public Vaccination(Health health, Farm farm, VaccineType vaccineType,
			Date lastVaccinationDate, Date nextVaccinationDate,
			Date vaccinationDate, Date manufacturedDate, String vaccineBrand,
			String manufacturerName, Date vaccineExpiryDate, BigDecimal dosage) {
		this.health = health;
		this.farm = farm;
		this.vaccineType = vaccineType;
		this.lastVaccinationDate = lastVaccinationDate;
		this.nextVaccinationDate = nextVaccinationDate;
		this.vaccinationDate = vaccinationDate;
		this.manufacturedDate = manufacturedDate;
		this.vaccineBrand = vaccineBrand;
		this.manufacturerName = manufacturerName;
		this.vaccineExpiryDate = vaccineExpiryDate;
		this.dosage = dosage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Health getHealth() {
		return this.health;
	}

	public void setHealth(Health health) {
		this.health = health;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public VaccineType getVaccineType() {
		return this.vaccineType;
	}

	public void setVaccineType(VaccineType vaccineType) {
		this.vaccineType = vaccineType;
	}

	public Date getLastVaccinationDate() {
		return this.lastVaccinationDate;
	}

	public void setLastVaccinationDate(Date lastVaccinationDate) {
		this.lastVaccinationDate = lastVaccinationDate;
	}

	public Date getNextVaccinationDate() {
		return this.nextVaccinationDate;
	}

	public void setNextVaccinationDate(Date nextVaccinationDate) {
		this.nextVaccinationDate = nextVaccinationDate;
	}

	public Date getVaccinationDate() {
		return this.vaccinationDate;
	}

	public void setVaccinationDate(Date vaccinationDate) {
		this.vaccinationDate = vaccinationDate;
	}

	public Date getManufacturedDate() {
		return this.manufacturedDate;
	}

	public void setManufacturedDate(Date manufacturedDate) {
		this.manufacturedDate = manufacturedDate;
	}

	public String getVaccineBrand() {
		return this.vaccineBrand;
	}

	public void setVaccineBrand(String vaccineBrand) {
		this.vaccineBrand = vaccineBrand;
	}

	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	public Date getVaccineExpiryDate() {
		return this.vaccineExpiryDate;
	}

	public void setVaccineExpiryDate(Date vaccineExpiryDate) {
		this.vaccineExpiryDate = vaccineExpiryDate;
	}

	public BigDecimal getDosage() {
		return this.dosage;
	}

	public void setDosage(BigDecimal dosage) {
		this.dosage = dosage;
	}

}