package com.dblue.farm;

// Generated Aug 23, 2012 11:41:12 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * IngredientOptions generated by hbm2java
 */
public class IngredientOptions extends FarmObjectImpl {

	private Integer id;
	private IngredientType ingredientType;
	private String label;
	private BigDecimal value;
	private Farm farm;

	public IngredientOptions() {
	}

	public IngredientOptions(IngredientType ingredientType, String label,
			BigDecimal value, Farm farm) {
		this.ingredientType = ingredientType;
		this.label = label;
		this.value = value;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public IngredientType getIngredientType() {
		return this.ingredientType;
	}

	public void setIngredientType(IngredientType ingredientType) {
		this.ingredientType = ingredientType;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
