package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PromotionHistory generated by hbm2java
 */
public class PromotionHistory extends FarmObjectImpl {

	private Integer id;
	private Livestock livestock;
	private StateType stateTypeByFinalStateType;
	private StateType stateTypeByInitialStateType;
	private Date promotionDate;
	private Farm farm;

	public PromotionHistory() {
	}

	public PromotionHistory(Livestock livestock,
			StateType stateTypeByFinalStateType,
			StateType stateTypeByInitialStateType, Date promotionDate, Farm farm) {
		this.livestock = livestock;
		this.stateTypeByFinalStateType = stateTypeByFinalStateType;
		this.stateTypeByInitialStateType = stateTypeByInitialStateType;
		this.promotionDate = promotionDate;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Livestock getLivestock() {
		return this.livestock;
	}

	public void setLivestock(Livestock livestock) {
		this.livestock = livestock;
	}

	public StateType getStateTypeByFinalStateType() {
		return this.stateTypeByFinalStateType;
	}

	public void setStateTypeByFinalStateType(StateType stateTypeByFinalStateType) {
		this.stateTypeByFinalStateType = stateTypeByFinalStateType;
	}

	public StateType getStateTypeByInitialStateType() {
		return this.stateTypeByInitialStateType;
	}

	public void setStateTypeByInitialStateType(
			StateType stateTypeByInitialStateType) {
		this.stateTypeByInitialStateType = stateTypeByInitialStateType;
	}

	public Date getPromotionDate() {
		return this.promotionDate;
	}

	public void setPromotionDate(Date promotionDate) {
		this.promotionDate = promotionDate;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
