package com.dblue.farm;

// Generated Sep 22, 2012 5:37:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VaccineType generated by hbm2java
 */
public class VaccineType extends FarmObjectImpl {

	private Integer id;
	private String vaccine;
	private String description;
	private Farm farm;
	private Integer intervalPeriod;
	private Set vaccinations = new HashSet(0);

	public VaccineType() {
	}

	public VaccineType(String vaccine, Farm farm) {
		this.vaccine = vaccine;
		this.farm = farm;
	}

	public VaccineType(String vaccine, String description, Farm farm,
			Integer intervalPeriod, Set vaccinations) {
		this.vaccine = vaccine;
		this.description = description;
		this.farm = farm;
		this.intervalPeriod = intervalPeriod;
		this.vaccinations = vaccinations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVaccine() {
		return this.vaccine;
	}

	public void setVaccine(String vaccine) {
		this.vaccine = vaccine;
	}

	public String getDescription() {
		return this.description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIntervalPeriod() {
		return this.intervalPeriod;
	}

	public void setIntervalPeriod(Integer intervalPeriod) {
		this.intervalPeriod = intervalPeriod;
	}

	public Set getVaccinations() {
		return this.vaccinations;
	}

	public void setVaccinations(Set vaccinations) {
		this.vaccinations = vaccinations;
	}
	
	@Override
	public String toString() {
		return vaccine;
	}

}
