package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address extends FarmObjectImpl {

	private Integer id;
	private Contact contact;
	private String line1;
	private String line2;
	private String line3;
	private String city;
	private String state;
	private String zip;
	private String country;
	private String type;

	public Address() {
	}

	public Address(String type) {
		this.type = type;
	}

	public Address(Contact contact, String line1, String line2, String line3,
			String city, String state, String zip, String country, String type) {
		this.contact = contact;
		this.line1 = line1;
		this.line2 = line2;
		this.line3 = line3;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	public String getLine3() {
		return this.line3;
	}

	public void setLine3(String line3) {
		this.line3 = line3;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getReadableAddress() {
		StringBuffer displayAddress = new StringBuffer();
		if(null!=line1){
			displayAddress.append(line1).append(", ");			
		}
		if(null!=line2){
			displayAddress.append(line2).append(", ");			
		}
		if(null!=line3){
			displayAddress.append(line3).append(", ");			
		}
		if(null!=city){
			displayAddress.append(city).append(", ");			
		}
		if(null!=state){
			displayAddress.append(state).append(", ");			
		}
		if(null!=country){
			displayAddress.append(country).append(", ");			
		}
		if(null!=zip){
			displayAddress.append(zip).append(" ");			
		}
		displayAddress.append(".");
		
		return displayAddress.toString();
		//return line1+", "+line2+", "+line3 +", "+city+", "+state+", "+country+", "+zip+".";
	}

}
