package com.dblue.farm;

// Generated Sep 15, 2012 12:11:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Asset generated by hbm2java
 */
public class Asset extends FarmObjectImpl {

	private Integer id;
	private Farm farm;
	private AssetType assetType;
	private String assetCode;
	private String assetName;
	private Date purchaseDate;
	private BigDecimal quantitiy;
	private BigDecimal unitCost;
	private String description;
	private String remarks;
	private BigDecimal totalCost;
	private Date warrantyEndDate;

	public Asset() {
	}

	public Asset(Farm farm, AssetType assetType, String assetCode,
			String assetName, Date purchaseDate, BigDecimal quantitiy,
			BigDecimal unitCost, String description, BigDecimal totalCost) {
		this.farm = farm;
		this.assetType = assetType;
		this.assetCode = assetCode;
		this.assetName = assetName;
		this.purchaseDate = purchaseDate;
		this.quantitiy = quantitiy;
		this.unitCost = unitCost;
		this.description = description;
		this.totalCost = totalCost;
	}

	public Asset(Farm farm, AssetType assetType, String assetCode,
			String assetName, Date purchaseDate, BigDecimal quantitiy,
			BigDecimal unitCost, String description, String remarks,
			BigDecimal totalCost, Date warrantyEndDate) {
		this.farm = farm;
		this.assetType = assetType;
		this.assetCode = assetCode;
		this.assetName = assetName;
		this.purchaseDate = purchaseDate;
		this.quantitiy = quantitiy;
		this.unitCost = unitCost;
		this.description = description;
		this.remarks = remarks;
		this.totalCost = totalCost;
		this.warrantyEndDate = warrantyEndDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public AssetType getAssetType() {
		return this.assetType;
	}

	public void setAssetType(AssetType assetType) {
		this.assetType = assetType;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getAssetName() {
		return this.assetName;
	}

	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public BigDecimal getQuantitiy() {
		return this.quantitiy;
	}

	public void setQuantitiy(BigDecimal quantitiy) {
		this.quantitiy = quantitiy;
	}

	public BigDecimal getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(BigDecimal unitCost) {
		this.unitCost = unitCost;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public BigDecimal getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	public Date getWarrantyEndDate() {
		return this.warrantyEndDate;
	}

	public void setWarrantyEndDate(Date warrantyEndDate) {
		this.warrantyEndDate = warrantyEndDate;
	}

}
