package com.dblue.farm;

import java.util.HashSet;
import java.util.Set;

// Generated 19 Jun, 2012 2:27:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssetType generated by hbm2java
 */
public class AssetType extends FarmObjectImpl {

	private Integer id;
	private String asset;
	private String description;
	private Farm farm;
	private Set assets = new HashSet(0);

	public AssetType() {
	}

	public AssetType(String asset, Farm farm) {
		this.asset = asset;
		this.farm = farm;
	}

	public AssetType(String asset, Farm farm, Set assets) {
		this.asset = asset;
		this.farm = farm;
		this.assets = assets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAsset() {
		return this.asset;
	}

	public void setAsset(String asset) {
		this.asset = asset;
	}
	
	public String getDescription() {
		return this.description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getAssets() {
		return this.assets;
	}

	public void setAssets(Set assets) {
		this.assets = assets;
	}

	@Override
	public String toString() {
		return asset;
	}
	
	

}
