package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BreedType generated by hbm2java
 */
public class BreedType extends FarmObjectImpl {

	private Integer id;
	private String breedType;
	private String description;
	private Set livestocksForBreedTypeId = new HashSet(0);
	private Set livestocksForMotherBreedId = new HashSet(0);
	private Farm farm;

	public BreedType() {
	}

	public BreedType(String breedType, Farm farm) {
		this.breedType = breedType;
		this.farm = farm;
	}

	public BreedType(String breedType, String description,
			Set livestocksForBreedTypeId, Set livestocksForMotherBreedId, Farm farm) {
		this.breedType = breedType;
		this.description = description;
		this.livestocksForBreedTypeId = livestocksForBreedTypeId;
		this.livestocksForMotherBreedId = livestocksForMotherBreedId;
		this.farm=farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBreedType() {
		return this.breedType;
	}

	public void setBreedType(String breedType) {
		this.breedType = breedType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getLivestocksForBreedTypeId() {
		return this.livestocksForBreedTypeId;
	}

	public void setLivestocksForBreedTypeId(Set livestocksForBreedTypeId) {
		this.livestocksForBreedTypeId = livestocksForBreedTypeId;
	}

	public Set getLivestocksForMotherBreedId() {
		return this.livestocksForMotherBreedId;
	}

	public void setLivestocksForMotherBreedId(Set livestocksForMotherBreedId) {
		this.livestocksForMotherBreedId = livestocksForMotherBreedId;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return breedType;
	}

}
