package com.dblue.farm;

// Generated 19 Jun, 2012 2:27:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact extends FarmObjectImpl {

	private Integer id;
	private String name;
	private String phoneNumber1;
	private String phoneNumber2;
	private String phoneNumber3;
	private String emailId;
	private Farm farm;
	private Set addresses = new HashSet(0);
	private Set persons = new HashSet(0);
	private Set farms = new HashSet(0);
	private Set vendors = new HashSet(0);

	public Contact() {
	}
	
	public Contact(Farm farm){
		this.farm = farm;
	}

	public Contact(String name, String phoneNumber1, String phoneNumber2,
			String phoneNumber3, String emailId, Farm farm, Set addresses, Set persons,
			Set farms, Set vendors) {
		this.name = name;
		this.phoneNumber1 = phoneNumber1;
		this.phoneNumber2 = phoneNumber2;
		this.phoneNumber3 = phoneNumber3;
		this.emailId = emailId;
		this.farm = farm;
		this.addresses = addresses;
		this.persons = persons;
		this.farms = farms;
		this.vendors = vendors;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber1() {
		return this.phoneNumber1;
	}

	public void setPhoneNumber1(String phoneNumber1) {
		this.phoneNumber1 = phoneNumber1;
	}

	public String getPhoneNumber2() {
		return this.phoneNumber2;
	}

	public void setPhoneNumber2(String phoneNumber2) {
		this.phoneNumber2 = phoneNumber2;
	}

	public String getPhoneNumber3() {
		return this.phoneNumber3;
	}

	public void setPhoneNumber3(String phoneNumber3) {
		this.phoneNumber3 = phoneNumber3;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getAddresses() {
		return this.addresses;
	}
	
	public Address getPermanentAddress(){
		
		Iterator addressIterator = addresses.iterator();		
		
		while( addressIterator.hasNext())
		{
			Address permAddress = (Address) addressIterator.next();
			if ( "P".equals(permAddress.getType())){
				return  permAddress;
			}
		}
		return null;
	}
	
public Address getTemporaryAddress(){
		
		Iterator addressIterator = addresses.iterator();		
		
		while( addressIterator.hasNext())
		{
			Address permAddress = (Address) addressIterator.next();
			if ( "T".equals(permAddress.getType())){
				return  permAddress;
			}
		}
		return null;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	public Set getFarms() {
		return this.farms;
	}

	public void setFarms(Set farms) {
		this.farms = farms;
	}

	public Set getVendors() {
		return this.vendors;
	}

	public void setVendors(Set vendors) {
		this.vendors = vendors;
	}

}
