package com.dblue.farm;

// Generated Sep 19, 2012 11:28:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Decease generated by hbm2java
 */
public class Decease extends FarmObjectImpl {

	private Integer id;
	private Health health;
	private Farm farm;
	private DeceaseType deceaseType;
	private Date startDate;
	private Date endDate;
	private Date treatmentDate;
	private String treatmentDescription;
	private String medicine;
	private String remarks;
	private String symptoms;

	public Decease() {
	}

	public Decease(DeceaseType deceaseType, Farm farm, String treatmentDescription,
			String medicine) {
		this.deceaseType = deceaseType;
		this.farm = farm;
		this.treatmentDescription = treatmentDescription;
		this.medicine = medicine;
	}

	public Decease(Health health, Farm farm, DeceaseType deceaseType, Date startDate,
			Date endDate, Date treatmentDate, String treatmentDescription,
			String medicine, String remarks) {
		this.health = health;
		this.farm = farm;
		this.deceaseType = deceaseType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.treatmentDate = treatmentDate;
		this.treatmentDescription = treatmentDescription;
		this.medicine = medicine;
		this.remarks = remarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Health getHealth() {
		return this.health;
	}

	public void setHealth(Health health) {
		this.health = health;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public DeceaseType getDeceaseType() {
		return this.deceaseType;
	}

	public void setDeceaseType(DeceaseType deceaseType) {
		this.deceaseType = deceaseType;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getTreatmentDate() {
		return this.treatmentDate;
	}

	public void setTreatmentDate(Date treatmentDate) {
		this.treatmentDate = treatmentDate;
	}

	public String getTreatmentDescription() {
		return this.treatmentDescription;
	}

	public void setTreatmentDescription(String treatmentDescription) {
		this.treatmentDescription = treatmentDescription;
	}

	public String getMedicine() {
		return this.medicine;
	}

	public void setMedicine(String medicine) {
		this.medicine = medicine;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getSymptoms() {
		return symptoms;
	}

	public void setSymptoms(String symptoms) {
		this.symptoms = symptoms;
	}

}