package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeedType generated by hbm2java
 */
public class FeedType extends FarmObjectImpl {

	private Integer id;
	private String feedType;
	private String description;
	private Farm farm;
	private Set feedingHistories = new HashSet(0);
	private Set feedingConfigs = new HashSet(0);

	public FeedType() {
	}

	public FeedType(String feedType, Farm farm) {
		this.feedType = feedType;
		this.farm = farm;
	}

	public FeedType(String feedType, String description, Farm farm, Set feedingHistories,
			Set feedingConfigs) {
		this.feedType = feedType;
		this.description = description;
		this.farm = farm;
		this.feedingHistories = feedingHistories;
		this.feedingConfigs = feedingConfigs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFeedType() {
		return this.feedType;
	}

	public void setFeedType(String feedType) {
		this.feedType = feedType;
	}

	public String getDescription() {
		return this.description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getFeedingHistories() {
		return this.feedingHistories;
	}

	public void setFeedingHistories(Set feedingHistories) {
		this.feedingHistories = feedingHistories;
	}

	public Set getFeedingConfigs() {
		return this.feedingConfigs;
	}

	public void setFeedingConfigs(Set feedingConfigs) {
		this.feedingConfigs = feedingConfigs;
	}
	
	@Override
	public String toString() {
		return feedType;
	}

}
