package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Health generated by hbm2java
 */
public class Health extends FarmObjectImpl {

	private Integer id;
	private Farm farm;
	private Set deceases = new HashSet(0);
	private Set devermitizations = new HashSet(0);
	private Set livestocks = new HashSet(0);
	private Set vaccinations = new HashSet(0);

	public Health() {
	}

	public Health(Farm farm, Set deceases, Set devermitizations, Set livestocks,
			Set vaccinations) {
		this.farm = farm;
		this.deceases = deceases;
		this.devermitizations = devermitizations;
		this.livestocks = livestocks;
		this.vaccinations = vaccinations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getDeceases() {
		return this.deceases;
	}

	public void setDeceases(Set deceases) {
		this.deceases = deceases;
	}

	public Set getDevermitizations() {
		return this.devermitizations;
	}

	public void setDevermitizations(Set devermitizations) {
		this.devermitizations = devermitizations;
	}

	public Set getLivestocks() {
		return this.livestocks;
	}

	public void setLivestocks(Set livestocks) {
		this.livestocks = livestocks;
	}

	public Set getVaccinations() {
		return this.vaccinations;
	}

	public void setVaccinations(Set vaccinations) {
		this.vaccinations = vaccinations;
	}

}
