package com.dblue.farm;

// Generated Aug 22, 2012 6:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * IngredientType generated by hbm2java
 */
public class IngredientType extends FarmObjectImpl {

	private Integer id;
	private String ingredient;
	private String description;
	private Farm farm;
	private Set ingredients = new HashSet(0);

	public IngredientType() {
	}

	public IngredientType(String ingredient,String description, Farm farm) {
		this.ingredient = ingredient;
		this.description=description;
		this.farm = farm;
	}

	public IngredientType(String ingredient, String description, Farm farm, Set ingredients) {
		this.ingredient = ingredient;
		this.description = description;
		this.farm = farm;
		this.ingredients = ingredients;
	}
	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(String ingredient) {
		this.ingredient = ingredient;
	}

	public Set getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Set ingredients) {
		this.ingredients = ingredients;
	}
	
	@Override
	public String toString() {
		return ingredient;
	}


}
