package com.dblue.farm;

// Generated Sep 7, 2012 7:36:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductionConfig generated by hbm2java
 */
public class ProductionConfig extends FarmObjectImpl {

	private Integer id;
	private String yeildSlotName;
	private int order;
	private Farm farm;
	private Set productionFarms = new HashSet(0);
	private Set productions = new HashSet(0);

	public ProductionConfig() {
	}

	public ProductionConfig(String yeildSlotName, int order, Farm farm) {
		this.yeildSlotName = yeildSlotName;
		this.order = order;
		this.farm = farm;
	}

	public ProductionConfig(String yeildSlotName, int order,
			Set productionFarms, Set productions) {
		this.yeildSlotName = yeildSlotName;
		this.order = order;
		this.farm = farm;
		this.productionFarms = productionFarms;
		this.productions = productions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYeildSlotName() {
		return this.yeildSlotName;
	}

	public void setYeildSlotName(String yeildSlotName) {
		this.yeildSlotName = yeildSlotName;
	}

	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getProductionFarms() {
		return this.productionFarms;
	}

	public void setProductionFarms(Set productionFarms) {
		this.productionFarms = productionFarms;
	}

	public Set getProductions() {
		return this.productions;
	}

	public void setProductions(Set productions) {
		this.productions = productions;
	}

}
