package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StateType generated by hbm2java
 */
public class StateType extends FarmObjectImpl {

	private Integer id;
	private String stateType;
	private String description;
	private Set livestocks = new HashSet(0);
	private Set promotionHistoriesForInitialStateType = new HashSet(0);
	private Set promotionHistoriesForFinalStateType = new HashSet(0);
	private Farm farm;

	public StateType() {
	}

	public StateType(String stateType, Farm farm) {
		this.stateType = stateType;
		this.farm = farm;
	}

	public StateType(String stateType, String description, Set livestocks,
			Set promotionHistoriesForInitialStateType,
			Set promotionHistoriesForFinalStateType, Farm farm) {
		this.stateType = stateType;
		this.description = description;
		this.livestocks = livestocks;
		this.promotionHistoriesForInitialStateType = promotionHistoriesForInitialStateType;
		this.promotionHistoriesForFinalStateType = promotionHistoriesForFinalStateType;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStateType() {
		return this.stateType;
	}

	public void setStateType(String stateType) {
		this.stateType = stateType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getLivestocks() {
		return this.livestocks;
	}

	public void setLivestocks(Set livestocks) {
		this.livestocks = livestocks;
	}

	public Set getPromotionHistoriesForInitialStateType() {
		return this.promotionHistoriesForInitialStateType;
	}

	public void setPromotionHistoriesForInitialStateType(
			Set promotionHistoriesForInitialStateType) {
		this.promotionHistoriesForInitialStateType = promotionHistoriesForInitialStateType;
	}

	public Set getPromotionHistoriesForFinalStateType() {
		return this.promotionHistoriesForFinalStateType;
	}

	public void setPromotionHistoriesForFinalStateType(
			Set promotionHistoriesForFinalStateType) {
		this.promotionHistoriesForFinalStateType = promotionHistoriesForFinalStateType;
	}
		
	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	@Override
	public String toString() {
		return stateType;
	}

}
