package com.dblue.farm;

// Generated 4 Aug, 2012 4:27:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SuggestedFeeding generated by hbm2java
 */
public class SuggestedFeeding extends FarmObjectImpl{

	private Integer id;
	private String stateType;
	private String feedType;
	private int feedQuantity;
	private Integer livestockTotal;
	private Date schduledDate;
	private Farm farm;

	public SuggestedFeeding() {
	}

	public SuggestedFeeding(String stateType, String feedType,
			int feedQuantity, Date schduledDate, Farm farm) {
		this.stateType = stateType;
		this.feedType = feedType;
		this.feedQuantity = feedQuantity;
		this.schduledDate = schduledDate;
		this.farm = farm;
	}

	public SuggestedFeeding(String stateType, String feedType,
			int feedQuantity, Integer livestockTotal, Date schduledDate, Farm farm) {
		this.stateType = stateType;
		this.feedType = feedType;
		this.feedQuantity = feedQuantity;
		this.livestockTotal = livestockTotal;
		this.schduledDate = schduledDate;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStateType() {
		return this.stateType;
	}

	public void setStateType(String stateType) {
		this.stateType = stateType;
	}

	public String getFeedType() {
		return this.feedType;
	}

	public void setFeedType(String feedType) {
		this.feedType = feedType;
	}

	public int getFeedQuantity() {
		return this.feedQuantity;
	}

	public void setFeedQuantity(int feedQuantity) {
		this.feedQuantity = feedQuantity;
	}

	public Integer getLivestockTotal() {
		return this.livestockTotal;
	}

	public void setLivestockTotal(Integer livestockTotal) {
		this.livestockTotal = livestockTotal;
	}

	public Date getSchduledDate() {
		return this.schduledDate;
	}

	public void setSchduledDate(Date schduledDate) {
		this.schduledDate = schduledDate;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
