package com.dblue.farm;

// Generated Sep 7, 2012 7:36:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Farm generated by hbm2java
 */
public class Farm extends FarmObjectImpl {

	private Integer id;
	private Contact contact;
	private String name;
	private String registrationNumber;
	private Set persons = new HashSet(0);
	private Set expenseses = new HashSet(0);
	private Set vendors = new HashSet(0);
	private Set inventories = new HashSet(0);
	private Set purchaseses = new HashSet(0);
	private Set livestocks = new HashSet(0);
	private Set stockTypes = new HashSet(0);
	private Set productionFarms = new HashSet(0);
	private Set productions = new HashSet(0);
	private Set assets = new HashSet(0);

	public Farm() {
	}

	public Farm(String name, String registrationNumber) {
		this.name = name;
		this.registrationNumber = registrationNumber;
	}

	public Farm(Contact contact, String name, String registrationNumber,
			Set persons, Set expenseses, Set vendors, Set inventories,
			Set purchaseses, Set livestocks, Set stockTypes,
			Set productionFarms, Set productions, Set assets) {
		this.contact = contact;
		this.name = name;
		this.registrationNumber = registrationNumber;
		this.persons = persons;
		this.expenseses = expenseses;
		this.vendors = vendors;
		this.inventories = inventories;
		this.purchaseses = purchaseses;
		this.livestocks = livestocks;
		this.stockTypes = stockTypes;
		this.productionFarms = productionFarms;
		this.productions = productions;
		this.assets = assets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	public Set getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set expenseses) {
		this.expenseses = expenseses;
	}

	public Set getVendors() {
		return this.vendors;
	}

	public void setVendors(Set vendors) {
		this.vendors = vendors;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

	public Set getPurchaseses() {
		return this.purchaseses;
	}

	public void setPurchaseses(Set purchaseses) {
		this.purchaseses = purchaseses;
	}

	public Set getLivestocks() {
		return this.livestocks;
	}

	public void setLivestocks(Set livestocks) {
		this.livestocks = livestocks;
	}

	public Set getStockTypes() {
		return this.stockTypes;
	}

	public void setStockTypes(Set stockTypes) {
		this.stockTypes = stockTypes;
	}

	public Set getProductionFarms() {
		return this.productionFarms;
	}

	public void setProductionFarms(Set productionFarms) {
		this.productionFarms = productionFarms;
	}

	public Set getProductions() {
		return this.productions;
	}

	public void setProductions(Set productions) {
		this.productions = productions;
	}

	public Set getAssets() {
		return this.assets;
	}

	public void setAssets(Set assets) {
		this.assets = assets;
	}

}
