package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Provisions generated by hbm2java
 */
public class Provisions extends FarmObjectImpl {

	private Integer id;
	private String provisionName;
	private Farm farm;
	private Set provisionInventories = new HashSet(0);

	public Provisions() {
	}

	public Provisions(String provisionName, Farm farm) {
		this.provisionName = provisionName;
		this.farm = farm;
	}

	public Provisions(String provisionName, Farm farm, Set provisionInventories) {
		this.provisionName = provisionName;
		this.farm = farm;
		this.provisionInventories = provisionInventories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvisionName() {
		return this.provisionName;
	}

	public void setProvisionName(String provisionName) {
		this.provisionName = provisionName;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getProvisionInventories() {
		return this.provisionInventories;
	}

	public void setProvisionInventories(Set provisionInventories) {
		this.provisionInventories = provisionInventories;
	}

}
