package com.dblue.farm;

// Generated Sep 10, 2012 7:31:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Reproduction generated by hbm2java
 */
public class Reproduction extends FarmObjectImpl {

	private Integer id;
	private Livestock livestock;
	private int lactationNumber;
	private String semenNumber;
	private Date semenGivenDate;
	private String remarks;
	private Date pregnencyTestDate;
	private Character pregnencyResult;
	private Date deliveryDate;
	private Integer numberOfCalfs;
	private String calfsSex;
	private Farm farm;

	public Reproduction() {
	}

	public Reproduction(Livestock livestock, int lactationNumber,
			String semenNumber, Date semenGivenDate, Farm farm) {
		this.livestock = livestock;
		this.lactationNumber = lactationNumber;
		this.semenNumber = semenNumber;
		this.semenGivenDate = semenGivenDate;
		this.farm = farm;
	}

	public Reproduction(Livestock livestock, int lactationNumber,
			String semenNumber, Date semenGivenDate, String remarks,
			Date pregnencyTestDate, Character pregnencyResult,
			Date deliveryDate, Integer numberOfCalfs, String calfsSex, Farm farm) {
		this.livestock = livestock;
		this.lactationNumber = lactationNumber;
		this.semenNumber = semenNumber;
		this.semenGivenDate = semenGivenDate;
		this.remarks = remarks;
		this.pregnencyTestDate = pregnencyTestDate;
		this.pregnencyResult = pregnencyResult;
		this.deliveryDate = deliveryDate;
		this.numberOfCalfs = numberOfCalfs;
		this.calfsSex = calfsSex;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Livestock getLivestock() {
		return this.livestock;
	}

	public void setLivestock(Livestock livestock) {
		this.livestock = livestock;
	}

	public int getLactationNumber() {
		return this.lactationNumber;
	}

	public void setLactationNumber(int lactationNumber) {
		this.lactationNumber = lactationNumber;
	}

	public String getSemenNumber() {
		return this.semenNumber;
	}

	public void setSemenNumber(String semenNumber) {
		this.semenNumber = semenNumber;
	}

	public Date getSemenGivenDate() {
		return this.semenGivenDate;
	}

	public void setSemenGivenDate(Date semenGivenDate) {
		this.semenGivenDate = semenGivenDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getPregnencyTestDate() {
		return this.pregnencyTestDate;
	}

	public void setPregnencyTestDate(Date pregnencyTestDate) {
		this.pregnencyTestDate = pregnencyTestDate;
	}

	public Character getPregnencyResult() {
		return this.pregnencyResult;
	}

	public void setPregnencyResult(Character pregnencyResult) {
		this.pregnencyResult = pregnencyResult;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Integer getNumberOfCalfs() {
		return this.numberOfCalfs;
	}

	public void setNumberOfCalfs(Integer numberOfCalfs) {
		this.numberOfCalfs = numberOfCalfs;
	}

	public String getCalfsSex() {
		return this.calfsSex;
	}

	public void setCalfsSex(String calfsSex) {
		this.calfsSex = calfsSex;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
