package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProvisionInventory generated by hbm2java
 */
public class ProvisionInventory extends FarmObjectImpl {

	private Integer id;
	private Provisions provisions;
	private Inventory inventory;
	private BigDecimal quantity;
	private BigDecimal unitPrice;
	private Date purchaseDate;
	private Farm farm;

	public ProvisionInventory() {
	}

	public ProvisionInventory(Provisions provisions, BigDecimal quantity,
			BigDecimal unitPrice, Farm farm) {
		this.provisions = provisions;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.farm = farm;
	}

	public ProvisionInventory(Provisions provisions, Inventory inventory,
			BigDecimal quantity, BigDecimal unitPrice, Date purchaseDate, Farm farm) {
		this.provisions = provisions;
		this.inventory = inventory;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.purchaseDate = purchaseDate;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Provisions getProvisions() {
		return this.provisions;
	}

	public void setProvisions(Provisions provisions) {
		this.provisions = provisions;
	}

	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
