package com.dblue.farm;

// Generated Sep 15, 2012 10:15:18 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Production generated by hbm2java
 */
public class Production extends FarmObjectImpl {

	private Integer id;
	private Livestock livestock;
	private Farm farm;
	private ProductionConfig productionConfig;
	private Date date;
	private BigDecimal yield;
	private BigDecimal fatPercentile;
	private int month;
	private BigDecimal snf;
	private BigDecimal clr;

	public Production() {
	}

	public Production(Farm farm, Date date, int month) {
		this.farm = farm;
		this.date = date;
		this.month = month;
	}

	public Production(Livestock livestock, Farm farm,
			ProductionConfig productionConfig, Date date, BigDecimal yield,
			BigDecimal fatPercentile, int month, BigDecimal snf, BigDecimal clr) {
		this.livestock = livestock;
		this.farm = farm;
		this.productionConfig = productionConfig;
		this.date = date;
		this.yield = yield;
		this.fatPercentile = fatPercentile;
		this.month = month;
		this.snf = snf;
		this.clr = clr;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Livestock getLivestock() {
		return this.livestock;
	}

	public void setLivestock(Livestock livestock) {
		this.livestock = livestock;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public ProductionConfig getProductionConfig() {
		return this.productionConfig;
	}

	public void setProductionConfig(ProductionConfig productionConfig) {
		this.productionConfig = productionConfig;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getYield() {
		return this.yield;
	}

	public void setYield(BigDecimal yield) {
		this.yield = yield;
	}

	public BigDecimal getFatPercentile() {
		return this.fatPercentile;
	}

	public void setFatPercentile(BigDecimal fatPercentile) {
		this.fatPercentile = fatPercentile;
	}

	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	public BigDecimal getSnf() {
		return this.snf;
	}

	public void setSnf(BigDecimal snf) {
		this.snf = snf;
	}

	public BigDecimal getClr() {
		return this.clr;
	}

	public void setClr(BigDecimal clr) {
		this.clr = clr;
	}

}
