package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory extends FarmObjectImpl {

	private Integer id;
	private Farm farm;
	private Set provisionInventories = new HashSet(0);

	public Inventory() {
	}

	public Inventory(Farm farm, Set provisionInventories) {
		this.farm = farm;
		this.provisionInventories = provisionInventories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public Set getProvisionInventories() {
		return this.provisionInventories;
	}

	public void setProvisionInventories(Set provisionInventories) {
		this.provisionInventories = provisionInventories;
	}

}
