package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Images generated by hbm2java
 */
public class Images extends FarmObjectImpl {

	private Integer id;
	private Livestock livestock;
	private byte[] rawImage;
	private Set persons = new HashSet(0);

	public Images() {
	}

	public Images(byte[] rawImage) {
		this.rawImage = rawImage;
	}

	public Images(Livestock livestock, byte[] rawImage, Set persons) {
		this.livestock = livestock;
		this.rawImage = rawImage;
		this.persons = persons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Livestock getLivestock() {
		return this.livestock;
	}

	public void setLivestock(Livestock livestock) {
		this.livestock = livestock;
	}

	public byte[] getRawImage() {
		return this.rawImage;
	}

	public void setRawImage(byte[] rawImage) {
		this.rawImage = rawImage;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

}
