package com.dblue.farm;

// Generated Nov 3, 2012 3:57:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StockCategory generated by hbm2java
 */
public class StockCategory extends FarmObjectImpl {

	private Integer id;
	private String stock;
	private String description;
	private Farm farm;
	private Set stockTypes = new HashSet(0);

	public StockCategory() {
	}

	public StockCategory(String stock, Farm farm) {
		this.stock = stock;
		this.farm = farm;
	}

	public StockCategory(String stock, Farm farm, Set stockTypes) {
		this.stock = stock;
		this.farm = farm;
		this.stockTypes = stockTypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStock() {
		return this.stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}
	
	public String getDescription() {
		return this.description;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getStockTypes() {
		return this.stockTypes;
	}

	public void setStockTypes(Set stockTypes) {
		this.stockTypes = stockTypes;
	}
	
	@Override
	public String toString() {
		return stock;
	}

}
