package com.dblue.farm;

// Generated 15 Jul, 2012 7:41:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeedingConfig generated by hbm2java
 */
public class FeedingConfig extends FarmObjectImpl {

	private Integer id;
	private FeedType feedType;
	private String feedSlotName;
	private int order;
	private Farm farm;

	public FeedingConfig() {
	}

	public FeedingConfig(FeedType feedType, String feedSlotName, int order, Farm farm) {
		this.feedType = feedType;
		this.feedSlotName = feedSlotName;
		this.order = order;
		this.farm = farm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FeedType getFeedType() {
		return this.feedType;
	}

	public void setFeedType(FeedType feedType) {
		this.feedType = feedType;
	}

	public String getFeedSlotName() {
		return this.feedSlotName;
	}

	public void setFeedSlotName(String feedSlotName) {
		this.feedSlotName = feedSlotName;
	}

	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	public Farm getFarm() {
		return farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

}
