package com.dblue.farm;

// Generated Sep 21, 2012 4:17:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

/**
 * Livestock generated by hbm2java
 */
public class Livestock extends FarmObjectImpl {

	private Integer id;
	private Health health;
	private MilkingStatus milkingStatus;
	private Farm farm;
	private BreedType breedTypeByBreedTypeId;
	private Vendor vendor;
	private Statistics statisticsByCurrentStatId;
	private BreedType breedTypeByMotherBreedId;
	private StateType stateType;
	private Statistics statisticsByPurchaseStatId;
	private OriginType originType;
	private String rfid;
	//private Integer lactationNumber;
	//private Date lactationDays;
	private Date birthDate;
	private Date conceivedDate;
	private String code;
	private String mothercode;
	private char sex;
	private char deceased;
	private Date deceasedDate;
	private String fatherSemenNumber;
	private String deliveryMode;
	private String initialValue;
	private String remarks;
	private String preferredType;
	private BigDecimal yeild;
	private BigDecimal fat;
	private Integer age;
	private Date stopMilkingDate;
	private Character stopMilkingStatus;
	private Character stopFeedingStatus;
	private Set productions = new HashSet(0);
	private Set feedingHistories = new HashSet(0);
	private Set expenseses = new HashSet(0);
	private Set reproductions = new HashSet(0);
	private Set purchaseses = new HashSet(0);
	private Set promotionHistories = new HashSet(0);
	private Set imageses = new HashSet(0);
	private Set lactations = new HashSet(0);
	//private Date dryoffDate;

	public Livestock() {
	}

	public Livestock(MilkingStatus milkingStatus, Farm farm,
			BreedType breedTypeByBreedTypeId,
			BreedType breedTypeByMotherBreedId, StateType stateType,
			OriginType originType, Date birthDate, char sex,char deceased,
			String preferredType) {
		this.milkingStatus = milkingStatus;
		this.farm = farm;
		this.breedTypeByBreedTypeId = breedTypeByBreedTypeId;
		this.breedTypeByMotherBreedId = breedTypeByMotherBreedId;
		this.stateType = stateType;
		this.originType = originType;
		this.birthDate = birthDate;
		this.sex = sex;
		this.preferredType = preferredType;
		this.deceased=deceased;		
	}

	public Livestock(Health health, MilkingStatus milkingStatus, Farm farm,
			BreedType breedTypeByBreedTypeId, Vendor vendor,
			Statistics statisticsByCurrentStatId,
			BreedType breedTypeByMotherBreedId, StateType stateType,
			Statistics statisticsByPurchaseStatId, OriginType originType,
			String rfid, 
			Date birthDate, Date conceivedDate, String code, String mothercode,
			char sex,char deceased, Date deceasedDate,String fatherSemenNumber, String deliveryMode,
			String initialValue, String remarks, String preferredType,
			BigDecimal yeild, BigDecimal fat, Integer age,
			Date stopMilkingDate, Character stopMilkingStatus,Character stopFeedingStatus, Set productions,
			Set feedingHistories, Set expenseses, Set reproductions,
			Set purchaseses, Set promotionHistories, Set imageses, Set lactations) {
		this.health = health;
		this.milkingStatus = milkingStatus;
		this.farm = farm;
		this.breedTypeByBreedTypeId = breedTypeByBreedTypeId;
		this.vendor = vendor;
		this.statisticsByCurrentStatId = statisticsByCurrentStatId;
		this.breedTypeByMotherBreedId = breedTypeByMotherBreedId;
		this.stateType = stateType;
		this.statisticsByPurchaseStatId = statisticsByPurchaseStatId;
		this.originType = originType;
		this.rfid = rfid;
//		this.lactationNumber = lactationNumber;
//		this.lactationDays = lactationDays;
		this.birthDate = birthDate;
		this.conceivedDate = conceivedDate;
		this.code = code;
		this.mothercode = mothercode;
		this.sex = sex;
		this.fatherSemenNumber = fatherSemenNumber;
		this.deliveryMode = deliveryMode;
		this.initialValue = initialValue;
		this.remarks = remarks;
		this.preferredType = preferredType;
		this.yeild = yeild;
		this.fat = fat;
		this.age = age;
		this.stopMilkingDate = stopMilkingDate;
		this.stopMilkingStatus = stopMilkingStatus;
		this.stopFeedingStatus = stopFeedingStatus;
		this.productions = productions;
		this.feedingHistories = feedingHistories;
		this.expenseses = expenseses;
		this.reproductions = reproductions;
		this.purchaseses = purchaseses;
		this.promotionHistories = promotionHistories;
		this.imageses = imageses;
		this.deceased=deceased;
		this.deceasedDate=deceasedDate;		
		this.lactations = lactations;
		//this.dryoffDate = dryoffDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Health getHealth() {
		return this.health;
	}

	public void setHealth(Health health) {
		this.health = health;
	}

	public MilkingStatus getMilkingStatus() {
		return this.milkingStatus;
	}

	public void setMilkingStatus(MilkingStatus milkingStatus) {
		this.milkingStatus = milkingStatus;
	}

	public Farm getFarm() {
		return this.farm;
	}

	public void setFarm(Farm farm) {
		this.farm = farm;
	}

	public BreedType getBreedTypeByBreedTypeId() {
		return this.breedTypeByBreedTypeId;
	}

	public void setBreedTypeByBreedTypeId(BreedType breedTypeByBreedTypeId) {
		this.breedTypeByBreedTypeId = breedTypeByBreedTypeId;
	}

	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	public Statistics getStatisticsByCurrentStatId() {
		return this.statisticsByCurrentStatId;
	}

	public void setStatisticsByCurrentStatId(
			Statistics statisticsByCurrentStatId) {
		this.statisticsByCurrentStatId = statisticsByCurrentStatId;
	}

	public BreedType getBreedTypeByMotherBreedId() {
		return this.breedTypeByMotherBreedId;
	}

	public void setBreedTypeByMotherBreedId(BreedType breedTypeByMotherBreedId) {
		this.breedTypeByMotherBreedId = breedTypeByMotherBreedId;
	}

	public StateType getStateType() {
		return this.stateType;
	}

	public void setStateType(StateType stateType) {
		this.stateType = stateType;
	}

	public Statistics getStatisticsByPurchaseStatId() {
		return this.statisticsByPurchaseStatId;
	}

	public void setStatisticsByPurchaseStatId(
			Statistics statisticsByPurchaseStatId) {
		this.statisticsByPurchaseStatId = statisticsByPurchaseStatId;
	}

	public OriginType getOriginType() {
		return this.originType;
	}

	public void setOriginType(OriginType originType) {
		this.originType = originType;
	}

	public String getRfid() {
		return this.rfid;
	}

	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

//	public Integer getLactationNumber() {
//		return this.lactationNumber;
//	}
//
//	public void setLactationNumber(Integer lactationNumber) {
//		this.lactationNumber = lactationNumber;
//	}
//
//	public Date getLactationDays() {
//		return this.lactationDays;
//	}
//
//	public void setLactationDays(Date lactationDays) {
//		this.lactationDays = lactationDays;
//	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getConceivedDate() {
		return this.conceivedDate;
	}

	public void setConceivedDate(Date conceivedDate) {
		this.conceivedDate = conceivedDate;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMothercode() {
		return this.mothercode;
	}

	public void setMothercode(String mothercode) {
		this.mothercode = mothercode;
	}

	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}
	
	public Boolean isActive(){
		return "N".equals(getDeceased());
	}

	public char getDeceased() {
		return deceased;
	}

	public void setDeceased(char deceased) {
		this.deceased = deceased;
	}	

	public Date getDeceasedDate() {
		return deceasedDate;
	}

	public void setDeceasedDate(Date deceasedDate) {
		this.deceasedDate = deceasedDate;
	}

	public String getFatherSemenNumber() {
		return this.fatherSemenNumber;
	}

	public void setFatherSemenNumber(String fatherSemenNumber) {
		this.fatherSemenNumber = fatherSemenNumber;
	}

	public String getDeliveryMode() {
		return this.deliveryMode;
	}

	public void setDeliveryMode(String deliveryMode) {
		this.deliveryMode = deliveryMode;
	}

	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getPreferredType() {
		return this.preferredType;
	}

	public void setPreferredType(String preferredType) {
		this.preferredType = preferredType;
	}

	public BigDecimal getYeild() {
		return this.yeild;
	}

	public void setYeild(BigDecimal yeild) {
		this.yeild = yeild;
	}

	public BigDecimal getFat() {
		return this.fat;
	}

	public void setFat(BigDecimal fat) {
		this.fat = fat;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getStopMilkingDate() {
		return this.stopMilkingDate;
	}

	public void setStopMilkingDate(Date stopMilkingDate) {
		this.stopMilkingDate = stopMilkingDate;
	}

	public Character getStopMilkingStatus() {
		return this.stopMilkingStatus;
	}

	public void setStopMilkingStatus(Character stopMilkingStatus) {
		this.stopMilkingStatus = stopMilkingStatus;
	}
		

	public Character getStopFeedingStatus() {
		return stopFeedingStatus;
	}

	public void setStopFeedingStatus(Character stopFeedingStatus) {
		this.stopFeedingStatus = stopFeedingStatus;
	}

	public Set getProductions() {
		return this.productions;
	}

	public void setProductions(Set productions) {
		this.productions = productions;
	}

	public Set getFeedingHistories() {
		return this.feedingHistories;
	}

	public void setFeedingHistories(Set feedingHistories) {
		this.feedingHistories = feedingHistories;
	}

	public Set getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set expenseses) {
		this.expenseses = expenseses;
	}

	public Set getReproductions() {
		return this.reproductions;
	}

	public void setReproductions(Set reproductions) {
		this.reproductions = reproductions;
	}

	public Set getPurchaseses() {
		return this.purchaseses;
	}

	public void setPurchaseses(Set purchaseses) {
		this.purchaseses = purchaseses;
	}

	public Set getPromotionHistories() {
		return this.promotionHistories;
	}

	public void setPromotionHistories(Set promotionHistories) {
		this.promotionHistories = promotionHistories;
	}

	public Set getImageses() {
		return this.imageses;
	}

	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

	public Set getLactations() {
		return lactations;
	}

	public void setLactations(Set lactations) {
		this.lactations = lactations;
	}

//	public Date getDryoffDate() {
//		return dryoffDate;
//	}
//
//	public void setDryoffDate(Date dryoffDate) {
//		this.dryoffDate = dryoffDate;
//	}
	
}
